trailing_comma:
    mandatory_comma: true

opt_in_rules:
  - fallthrough
  - implicit_return
  - let_var_whitespace
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - sorted_imports

analyzer_rules:
  - unused_import
